print("=+=+=+=+=+ DATA DIRI MAHASISWA +=+=+=+=+=+")
garis = ("======================================")
nim = input("NIM : ")
nama = input("NAMA LENGKAP : ")
usia = int(input("USIA : ")) 
jurusan = input("JURUSAN : ")
alamat = input("ALAMAT : ")
berat_badan = float(input("BERAT BADAN : ")) 
tinggi_badan = float(input("TINGGI BADAN : "))

print("Hasil cetak data diatas adalah")
print(garis)
print("NIM : " +str(nim))
print("NAMA : " +str(nama))
print("USIA :" +str(usia) + " TAHUN ")
print("JURUSAN : " +str(jurusan))
print("ALAMAT : " +str(alamat))
print("BERAT BADAN : " +str(berat_badan) + " Kg ")
print("TINGGI BADAN : " +str(tinggi_badan) + " Cm ")
print(garis)